"""
app/knowledge

Package exporting canonical BIS Knowledge Model, repository, and service.
"""

from app.knowledge.models import (
    Standard,
    StandardVersion,
    StandardPart,
    Clause,
    Amendment,
    StandardReference,
    StandardStatus,
    ReferenceType,
    ResolutionStatus,
    KnowledgeDiagnostics,
)
from app.knowledge.normalization import (
    normalize_standard_number,
    normalize_clause_number,
    derive_clause_hierarchy,
    derive_standard_id,
    derive_version_id,
    derive_version_key,
    derive_part_id,
    derive_clause_id,
    derive_amendment_id,
    derive_reference_id,
    classify_standard_relation,
    establishes_standard_identity,
    derive_clause_key,
    is_document_header_section,
    STANDARD_IDENTITY_DOCUMENT_TYPES,
    STANDARD_RELATION_IDENTITY,
    STANDARD_RELATION_REFERENCE,
    STANDARD_RELATION_NONE,
)
from app.knowledge.validator import validate_knowledge_graph
from app.knowledge.repository import KnowledgeRepository, default_repository
from app.knowledge.service import KnowledgeService, default_knowledge_service
from app.knowledge.join import (
    ChunkKnowledgeLink,
    resolve_chunk,
    resolve_results,
    resolve_version_for_chunk,
    summarize_links,
    chunk_ids_for_clause,
    chunk_ids_for_version,
    JOIN_METADATA_KEYS,
    RESOLUTION_RESOLVED,
    RESOLUTION_UNLINKED,
    RESOLUTION_DANGLING,
)

__all__ = [
    "Standard",
    "StandardVersion",
    "StandardPart",
    "Clause",
    "Amendment",
    "StandardReference",
    "StandardStatus",
    "ReferenceType",
    "ResolutionStatus",
    "KnowledgeDiagnostics",
    "normalize_standard_number",
    "normalize_clause_number",
    "derive_clause_hierarchy",
    "derive_standard_id",
    "derive_version_id",
    "derive_version_key",
    "derive_part_id",
    "derive_clause_id",
    "derive_amendment_id",
    "derive_reference_id",
    "classify_standard_relation",
    "establishes_standard_identity",
    "derive_clause_key",
    "is_document_header_section",
    "STANDARD_IDENTITY_DOCUMENT_TYPES",
    "STANDARD_RELATION_IDENTITY",
    "STANDARD_RELATION_REFERENCE",
    "STANDARD_RELATION_NONE",
    "validate_knowledge_graph",
    "KnowledgeRepository",
    "default_repository",
    "KnowledgeService",
    "default_knowledge_service",
    "ChunkKnowledgeLink",
    "resolve_chunk",
    "resolve_results",
    "resolve_version_for_chunk",
    "summarize_links",
    "chunk_ids_for_clause",
    "chunk_ids_for_version",
    "JOIN_METADATA_KEYS",
    "RESOLUTION_RESOLVED",
    "RESOLUTION_UNLINKED",
    "RESOLUTION_DANGLING",
]
