"""create initial BIS metadata tables

Revision ID: e0fbb702cbdb
Revises: 
Create Date: 2026-09-05 09:23:59.139629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0fbb702cbdb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_id'), 'sources', ['id'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('canonical_url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('page_type', sa.String(length=128), nullable=True),
    sa.Column('parent_url', sa.String(length=2048), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('subcategory', sa.String(length=255), nullable=True),
    sa.Column('content_hash', sa.String(length=255), nullable=True),
    sa.Column('crawl_status', sa.String(length=64), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'canonical_url', name='uq_page_source_canonical_url')
    )
    op.create_index(op.f('ix_pages_canonical_url'), 'pages', ['canonical_url'], unique=False)
    op.create_index(op.f('ix_pages_id'), 'pages', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('document_url', sa.String(length=2048), nullable=False),
    sa.Column('canonical_url', sa.String(length=2048), nullable=False),
    sa.Column('document_type', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('subcategory', sa.String(length=255), nullable=True),
    sa.Column('standard_number', sa.String(length=128), nullable=True),
    sa.Column('revision', sa.String(length=64), nullable=True),
    sa.Column('edition', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=255), nullable=True),
    sa.Column('crawl_status', sa.String(length=64), nullable=False),
    sa.Column('parse_status', sa.String(length=64), nullable=False),
    sa.Column('embedding_status', sa.String(length=64), nullable=False),
    sa.Column('parse_quality_score', sa.Float(), nullable=True),
    sa.Column('last_crawled_at', sa.DateTime(), nullable=True),
    sa.Column('last_parsed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'canonical_url', name='uq_document_source_canonical_url')
    )
    op.create_index(op.f('ix_documents_canonical_url'), 'documents', ['canonical_url'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('document_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('target_document_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['target_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_relationships_id'), 'document_relationships', ['id'], unique=False)
    op.create_table('document_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('version_label', sa.String(length=128), nullable=True),
    sa.Column('revision', sa.String(length=64), nullable=True),
    sa.Column('document_url', sa.String(length=2048), nullable=False),
    sa.Column('content_hash', sa.String(length=255), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_versions_id'), 'document_versions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_versions_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_document_relationships_id'), table_name='document_relationships')
    op.drop_table('document_relationships')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_canonical_url'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_pages_id'), table_name='pages')
    op.drop_index(op.f('ix_pages_canonical_url'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_sources_id'), table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###
